#!/bin/sh

filename="thesis_"`eval date +%Y%m%d-%H%M`
cd ..
tar czf $filename.tar.gz thesis
mv $filename.tar.gz /home/neuhaus/Documents/Dropbox/mestrado/bkp_tese
sudo chmod 755 -R /home/neuhaus/Documents/Dropbox/mestrado/bkp_tese
sudo chown neuhaus.neuhaus -R /home/neuhaus/Documents/Dropbox/mestrado/bkp_tese
echo DONE... $filename.tag.gz
